# Generated by Django 5.1.1 on 2025-09-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
    ]
