# Generated by Django 5.1.1 on 2025-09-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_auto_20250922_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avance_salaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Avance sur salaire'),
        ),
        migrations.AddField(
            model_name='employee',
            name='saisie_opposition',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saisie et opposition'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salaire_net_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire net à payer'),
        ),
    ]
