# Generated by Django 5.1.1 on 2025-09-23 14:35

import salary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_employee_avance_salaire_employee_saisie_opposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mon Entreprise', max_length=200, verbose_name="Nom de l'entreprise")),
                ('logo', models.ImageField(blank=True, help_text='Téléchargez le logo de votre entreprise (PNG, JPG, JPEG recommandés)', null=True, upload_to=salary.models.logo_upload_path, verbose_name="Logo de l'entreprise")),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
    ]
