# Generated by Django 5.2.6 on 2025-10-09 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("salary", "0004_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="autre_gratification",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="prime_craie",
        ),
    ]
