# Generated by Django 5.1.1 on 2025-12-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salary", "0006_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="avantage_nature",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Avantage en nature",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="prime_responsabilite",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Prime de responsabilité (taxable)",
            ),
        ),
    ]
